window.LESSON_NOTES = {
  intro: "From a short message to a difficult decision, reading asks us to do more than recognise words. Explore how useful support and repeated practice turn information into independent choices.",
  presentation: {
    topic: "EDUCATION, ADULT LEARNING & DIGITAL INCLUSION",
    footerTopic: "Adult learning & literacy",
    heroTitle: "Reading Is a Skill<br><em>We Must Keep Using.</em>",
    subtitle: "Understand the words. Make your own choices.",
    heroImage: "images/reference-0.webp",
    heroAlt: "An adult reads a document, surrounded by scenes of learning in a library, workplace and community",
    imageLayout: "wide",
    captionKicker: "READING IN EVERYDAY LIFE",
    caption: "A skill grows through opportunities to use it.",
    contextTitle: "Reading opens up everyday choices",
    contextDate: "International Literacy Day · 8 September 2026",
    contextFacts: [
      ["Access", "The opportunity to reach information"],
      ["Agency", "The ability to understand and act"]
    ],
    contextLink: "Why keep practising?",
    contextParagraph: "J",
    storyTitle: "From information to independence",
    storyFlow: "Access → Understand → Use",
    story: [
      {target:"A", label:"A — D · Understand the task", icon:"book", title:"What does reading let us do?", description:"Look beyond qualifications and connectivity. Ask what a reader can do with a document and its claims.", terms:"proficiency · inference"},
      {target:"E", label:"E — G · Make learning usable", icon:"layers", color:"teal", title:"What helps a skill develop?", description:"Connect temporary support, purposeful practice and flexible learning to the realities of adult life.", terms:"scaffold · engagement"},
      {target:"H", label:"H — J · Put understanding to work", icon:"light", color:"amber", title:"What makes learning last?", description:"Follow reading into community decisions, funding choices and unfamiliar tasks beyond a course.", terms:"agency · reinforce"}
    ],
    readingTitle: "Reading Is a Skill We Must Keep Using",
    facts: "Dated UNESCO, OECD, ITU and UIL accounts. Historical findings retain their original dates.",
    examples: "Rental agreements, applicants, shift workers and community meetings are hypothetical. Teaching and funding proposals are the author's reasoning.",
    compass: ["What does the text say?", "What am I inferring?", "Can I use this elsewhere?"],
    studyNote: "Begin with 20 closed-book prompts from Days 1 and 2. Read A–J and attempt the reading questions before opening the key. Then practise the vocabulary and write. Split the lesson into two sessions if useful.",
    recall: {
      hint: "Words from Days 1 & 2",
      eyebrow: "CLOSED-BOOK REVIEW · DAYS 1 & 2",
      title: "Bring earlier words into a new context",
      description: "Retrieve 10 expressions from Day 1 and 10 from Day 2 without a word bank. Attempt each prompt before opening its answer. Self-mark only what you recalled without looking."
    },
    writingType: "Two-part question · Causes and solutions",
    writingPrompt: "In many places, adults who need to improve their reading and writing skills do not take part in educational programmes.",
    writingQuestion: "What are the main reasons for this? What measures could encourage more adults to participate?",
    writingGuide: [
      ["Introduce both parts", "Outline the main barriers and the responses you will explain."],
      ["Explain the causes", "Show how work, care responsibilities or stigma affect the decision to join."],
      ["Match responses to barriers", "Connect each measure to a stated cause. Consider who might still be excluded."],
      ["Bring the answer together", "Summarise the matched responses without adding a new cause."]
    ],
    writingWords: ["accommodate different needs", "flexible arrangements", "practical relevance", "accessible provision"],
    challengePrompt: "A library wants more adults to join its learning programme. Recommend two changes and explain how each could help people participate.",
    challengeInstructions: "Plan for one minute, then write 80–120 words. Use at least five target expressions, one clear cause-and-effect relationship and one qualification with could, may or depends on. Match each change to an identifiable barrier.",
    challengeWords: ["stigma", "accommodate", "flexible", "relevance", "facilitator", "engagement", "autonomy", "provision"],
    challengeMode: "writing",
    challengePlaceholder: "Recommend two changes. Explain which barrier each addresses and how it could help.",
    qualification: "\\bmay\\b|\\bcould\\b|\\bdepends on\\b"
  },
  vocabulary: [
    "Understanding and using written language", "Providing an essential basis", "Making independent choices", "A level of practical skill", "A gradually varying range", "Reaching an educational level or goal", "A noticeable difference", "Little or no progress", "Unequal access to usable technology", "A price manageable within resources", "Find a way through a process", "Recognise through careful attention", "Worthy of trust", "Creating an incorrect impression", "A conclusion drawn from evidence", "Provide support that can be reduced", "Keeping information over time", "Usable in another setting", "Social disapproval", "Make arrangements for different needs", "Able to adapt to circumstances", "A useful connection to a need", "Someone who supports participation", "Learning at your own speed", "Active involvement and attention", "Capacity to act and influence", "Involvement in public decisions", "The value of the best alternative forgone", "Making a service available", "Strengthen something already developing"
  ],
  paragraphs: [
    {id:"A", title:"Reading makes independent choices possible", tag:"Literacy and autonomy", takeaway:"The reading task matters more than a simple literate/illiterate label.", explanation:"Reading a message and comparing rental agreements place different demands on a reader. The opening asks us to consider what someone needs to do with written information. Independent choice can include seeking help; autonomy does not mean refusing support.", question:"What does the rental-agreement example establish?", answer:"It illustrates why two labels tell us little about a specific task. It does not report a surveyed participant or rank housing documents above all other texts.", image:1, imageAlt:"A reader compares two housing documents and considers costs, conditions and services"},
    {id:"B", title:"A qualification and a current skill differ", tag:"Proficiency across a continuum", takeaway:"An average describes a group; it cannot establish every individual's progress.", explanation:"Educational attainment records completed education. Proficiency concerns current performance with a text. The OECD evidence is from December 2024, rather than a new September 2026 survey. A stagnant national average can coexist with improvements for some people and difficulties for others.", question:"Does a stable average prove that nobody improved?", answer:"No. Different individual changes can produce the same average. The national comparison also cannot establish the cause of one person's difficulty.", image:2, imageAlt:"Readers handle progressively more complex texts, from phone messages to multi-page documents"},
    {id:"C", title:"A connection opens only the first door", tag:"Digital access and understanding", takeaway:"Having a phone does not establish that someone can use a complicated form accurately.", explanation:"The dated ITU estimate concerns people offline in 2025. Among people with access, affordability, quality and usability can still differ. The invented applicant shows how reaching a form and understanding an exception to a rule are separate tasks. Teaching and clearer design address different parts of the burden.", question:"What does internet access enable, and what does it leave unresolved?", answer:"It enables an attempt. It does not supply comprehension, affordable ongoing use or a well-designed application process.", image:3, imageAlt:"A reader works through a digital form while considering connection, access and household costs"},
    {id:"D", title:"Read the size of a claim", tag:"Credibility and inference", takeaway:"'Some improved' establishes neither a majority nor the cause of the improvement.", explanation:"A claim can be technically accurate yet create a misleading impression. Discernment involves locating the evidence and noticing the limits of what is stated. The advertisement is invented to test an inference; the passage does not report a product trial or prove that every improvement claim is false.", question:"What extra evidence would justify 'the product caused improvement'?", answer:"Evidence connecting the product to the change, beyond the fact that some participants improved. The stated example supplies no basis for attributing causation.", image:4, imageAlt:"A reader examines a wellness advertisement with a magnifying glass rather than accepting its confident presentation"},
    {id:"E", title:"Support should prepare the next independent step", tag:"Scaffolding, retention and transfer", takeaway:"A supported answer, later recall and successful use in a new setting are different achievements.", explanation:"Scaffolding supplies temporary help that can gradually be withdrawn. Retention asks whether an idea remains available later, without the original prompt. Transfer asks whether an approach works in a different setting. These are proposed teaching choices rather than results of an evaluated programme.", question:"If someone repeats a visible example, have they demonstrated transfer?", answer:"No. Transfer requires using the approach successfully in a new setting. Later recall without the prompt would test retention instead.", image:5, imageAlt:"Temporary learning supports are gradually removed as an adult works independently on a new document"},
    {id:"F", title:"Make learning fit the lives around it", tag:"Practical and social barriers", takeaway:"A useful response addresses a specific barrier and is checked with learners.", explanation:"Stigma can discourage help-seeking. Irregular shifts can make a fixed class time difficult to attend. Flexible timetables may help, while practical materials can make scarce study time feel worthwhile. The shift worker and school notice are hypothetical examples; convenience should be checked rather than assumed.", question:"Does flexibility remove the need for structure?", answer:"No. Providers still need enough organisation to support learning. They should check whether the arrangement actually works for the learners involved."},
    {id:"G", title:"Reach is a starting point for evaluation", tag:"Facilitators and engagement", takeaway:"An educator course's reach does not by itself establish reading gains for every learner.", explanation:"The UIL account reports around 10,000 educators reached and eleven self-paced sessions. Self-paced describes timing and speed. Engagement describes meaningful participation. Reach does not supply a completion rate or evidence of downstream outcomes among every learner taught by the participants.", question:"Does the passage say that most educators completed every session?", answer:"No. It supplies reach and format, but no completion proportion. The answer is not given; lack of evidence is not proof that nobody completed the course."},
    {id:"H", title:"Understanding gives participation a voice", tag:"Agency and civic life", takeaway:"Reading can help people question public choices without guaranteeing agreement.", explanation:"Agency emphasises being able to pursue goals and influence circumstances. Civic participation extends literacy beyond employment and forms. The invented public-building example shows how understandable documents can support informed disagreement. Confidence and critical judgement can develop together.", question:"Why might disagreement still be a useful outcome?", answer:"People can disagree while sharing an accurate understanding of the options. This can be more useful than silence produced by confusion.", image:0, imageAlt:"Everyday reading connects individual choices with learning at work, in libraries and in community settings"},
    {id:"I", title:"Ask what a programme enables and leaves out", tag:"Opportunity cost and provision", takeaway:"Assess meaningful progress, accessibility and the best alternative use of resources.", explanation:"Opportunity cost is the value of the best alternative forgone, rather than the sum of every rejected option. The author supports serious consideration of adult learning but does not approve every course. Evaluation should include people unable to attend, as well as those already using the service.", question:"Why ask who is absent from a programme?", answer:"Results among people who can attend may miss the obstacles faced by others. The service may need changes before it can reach those with greater barriers."},
    {id:"J", title:"Keep giving a skill somewhere to go", tag:"Repeated use beyond the course", takeaway:"A lasting skill helps readers tackle unfamiliar tasks and continue learning independently.", explanation:"Libraries, workplaces and public services could provide repeated opportunities for purposeful reading. Success depends on teaching, access and practice conditions. The author distinguishes attention to literacy from changes learners can use in daily life, and rehearsed exercises from unfamiliar tasks.", question:"What does 'that' refer to in 'Whether new initiatives achieve that'?", answer:"Being better able to tackle unfamiliar tasks, rather than merely repeating the course's exercises. The whether-clause leaves the outcome open."}
  ],
  grammar: [
    {label:"AN -ING CLAUSE AS SUBJECT", title:"Name the action. Evaluate its usefulness.", chunks:["Calling this person either literate or illiterate", "would tell us little", "about the task they face."], roles:["Subject: an act of classification", "Conditional evaluation", "The task being explained"], tip:"The whole -ing clause is the subject. 'Would' evaluates an imagined classification; it does not report a measured finding.", notes:["Calling names an activity. Either … or joins the two labels within the subject clause.", "Would tell us little questions explanatory value rather than denying that the person can read anything.", "They face is a relative clause modifying task; an object relative pronoun is omitted."]},
    {label:"CONTRAST WITH AN EMBEDDED QUESTION", title:"Separate a recorded level from practical ability.", chunks:["Educational attainment records completed levels of education,", "whereas reading ability concerns", "what someone can actually do with a text."], roles:["Main clause: completed education", "Contrasting clause", "Embedded what-clause"], tip:"The embedded question uses statement order: what someone can do. Completed modifies levels; records is the main verb.", notes:["Attainment names a recorded educational level. Completed is a modifier, not the sentence's main verb.", "Whereas explicitly contrasts two ways of describing learning.", "The what-clause is the complement of concerns. Avoid the direct-question order 'what can someone do'."]},
    {label:"MEANS AND A PASSIVE RELATIVE", title:"Explain how support can develop independence.", chunks:["A useful lesson can scaffold a difficult task", "by supplying temporary support", "that is gradually withdrawn."], roles:["Main clause: a possibility", "Means: by + -ing", "Passive relative: which support"], tip:"By supplying states the means. That is gradually withdrawn defines the support and focuses on its removal.", notes:["Can proposes a possible benefit. It does not guarantee the result for every learner.", "By introduces the method. Supplying is a non-finite -ing form after the preposition.", "That modifies support. The passive is withdrawn leaves the person removing it unnamed."]},
    {label:"A RESPONSE WITH A QUALIFICATION", title:"Make arrangements without overgeneralising.", chunks:["Providers could accommodate such constraints", "through flexible timetables,", "without assuming that flexibility removes the need for structure."], roles:["Main clause: proposed response", "Means: timetable changes", "Assumption to avoid"], tip:"Such constraints points back to scheduling pressures. Providers is also the understood subject of assuming.", notes:["Could signals a proposal. Such constraints refers back to the pressures described immediately before the sentence.", "Through identifies a means of accommodating those pressures.", "Without introduces a non-finite clause. The following that-clause states the assumption the author warns against."]},
    {label:"A WHETHER-CLAUSE AS SUBJECT", title:"Keep the outcome open. Name its conditions.", chunks:["Whether new initiatives achieve that", "depends on teaching, access and the conditions", "in which people practise."], roles:["Subject clause: an open outcome", "Singular main verb and factors", "Relative clause: practice setting"], tip:"The whole whether-clause takes singular depends. That refers to tackling unfamiliar tasks; in which modifies conditions.", notes:["Whether leaves success undecided. That refers to unfamiliar tasks in the preceding sentence.", "Depends agrees with the subject clause as a whole, not with the plural initiatives inside it.", "In which is a formal relative expression connecting practice to the conditions in which it occurs."]}
  ],
  diagrams: {
    C: {type:"compare", title:"Reaching a form and using it are separate tasks", subtitle:"The hypothetical applicant in paragraph C", items:[["Access", "A connection and manageable cost make the attempt possible."], ["Understanding", "Finding the eligibility exception and applying it correctly make completion possible."]]},
    D: {type:"choices", title:"What follows from 'some participants improved'?", subtitle:"The invented advertisement in paragraph D", options:[["Some improved", "This is the limited statement supplied. It does not give a proportion or identify a cause."], ["Most improved", "This stronger conclusion is unsupported. Some does not establish that more than half improved."], ["The product caused it", "This causal conclusion is unsupported. Improvement alone does not show why it occurred."]]},
    E: {type:"choices", title:"Which achievement are we observing?", subtitle:"Proposed teaching steps, not trial results", options:[["Supported performance", "A learner answers successfully while the worked example is visible. This does not yet show later retention."], ["Later recall", "A learner explains the idea later without the original prompt. This checks whether the learning has been retained."], ["Use in a new setting", "A learner applies the approach to a different task successfully. This demonstrates transferable use."]]},
    G: {type:"compare", title:"The reported reach and its limits", subtitle:"UIL account described in the passage", items:[["Reported", "Around 10,000 educators reached; eleven self-paced sessions."], ["Not established", "A completion proportion or improved reading outcomes for every learner taught by those educators."]]},
    I: {type:"choices", title:"Which alternative matters to opportunity cost?", subtitle:"A hypothetical use of a study hour", options:[["Study for one hour", "Consider the best alternative use of this hour. If that is a paid shift, its forgone earnings are the opportunity cost."], ["Add every rejected option", "Do not add all possible uses together. Opportunity cost concerns the best alternative forgone, rather than every rejected possibility."]]}
  }
};
