window.LESSON_NOTES = {
  intro: "A farming method can cross an ocean more easily than it can become part of someone's working week. The useful question is whether it fits the land, the costs and the people who would have to keep it going.",
  presentation: {
    topic: "AGRICULTURE, COOPERATION & RURAL DEVELOPMENT",
    footerTopic: "Farming ideas across borders",
    heroTitle: "When Good Farming Ideas<br><em>Cross Borders.</em>",
    subtitle: "A method can cross an ocean. A routine has to be built.",
    heroImage: "images/reference-0.webp",
    heroAlt: "Farmers on two coasts examine seedlings, irrigation pipes and seed that have crossed the water between them",
    imageLayout: "wide",
    captionKicker: "FROM ONE FIELD TO ANOTHER",
    caption: "Arrival is not the same as adoption.",
    contextTitle: "A shared technique still needs a local test",
    contextDate: "UN South-South feature · 11 September 2026",
    contextFacts: [
      ["Reported", "Programme results, not a national average"],
      ["The test", "Can an ordinary household keep it going?"]
    ],
    contextLink: "What should remain?",
    contextParagraph: "J",
    storyTitle: "A technique has to earn its place",
    storyFlow: "Fit the farm → Keep it going → Judge the result",
    story: [
      {target:"A", label:"A — C · Judge the fit", icon:"book", title:"Does success elsewhere travel?", description:"A manual can cross a border and still miss the local routine. A demonstration can show potential without showing what every household can reproduce.", terms:"know-how · yield"},
      {target:"D", label:"D — F · Test the system", icon:"layers", color:"teal", title:"Can the wider routine continue?", description:"Separate a field trial from a pilot. Then follow water, repair, inputs, money and what neighbours actually keep using.", terms:"feasibility · uptake"},
      {target:"G", label:"G — J · Share the decision", icon:"light", color:"amber", title:"Who decides, and what caused the change?", description:"Local influence, unequal bargaining power and a recorded starting point come before any decision to scale up.", terms:"ownership · attribution"}
    ],
    readingTitle: "When Good Farming Ideas Cross Borders",
    facts: "Dated UN and FAO accounts of reported activities and programme results.",
    examples: "The village, the cost chain and the discussion of power are the article's analysis, not extra findings about those projects.",
    compass: ["Does it fit this farm?", "Can people keep it going?", "What else could explain the result?"],
    studyNote: "Attempt the 20 closed-book prompts from 7 September before you open an earlier list. Read A–J, answer all 15 reading questions, and only then open the explanations. Practise the vocabulary before you plan the essay and the speaking challenge. You can divide the lesson into two sessions.",
    readingTime: "20–23 minutes",
    recall: {
      hint: "20 words from 7 September",
      eyebrow: "CLOSED-BOOK REVIEW · 7 SEPTEMBER",
      title: "Recover the earlier words first",
      description: "These 20 items were taught on 7 September. No word bank is supplied. This is one catch-up exposure. Self-mark only what you recalled without looking."
    },
    writingType: "Discuss both views and give your opinion",
    writingPrompt: "Some people believe that the best way for wealthy countries to support developing countries is to provide money. Others believe that sharing practical skills and knowledge is more helpful.",
    writingQuestion: "Discuss both views and give your own opinion.",
    writingGuide: [
      ["Introduce both views", "Name financial support and practical knowledge, then state your own judgement."],
      ["Explain when money matters", "Show a constraint that existing local skill cannot remove without resources."],
      ["Explain when knowledge matters", "Show what lasts after funding or visiting specialists end, and where training still fails."],
      ["State the balance directly", "Keep the judgement tied to the constraint, not to a claim that one side always wins."]
    ],
    writingWords: ["access to capital", "invest in capacity building", "reduce dependence on", "strengthen local ownership"],
    challengePrompt: "A rural community has been offered a promising new farming method by an overseas partner. Explain what it should check before adopting the method widely.",
    challengeInstructions: "Plan for one minute, then speak for 60–90 seconds. Include one practical constraint, one way of involving local people and one way of evaluating results. Use at least five of the target expressions. Separate a promising result from proof of its cause.",
    challengeWords: ["pilot project", "feasibility", "local ownership", "baseline", "attribution", "viable", "scale up"],
    challengeMode: "speaking",
    challengePlaceholder: "Note five keywords. Speak without reading a script.",
    qualification: "\\bmay\\b|\\bcould\\b|\\bmight\\b|\\bnot proof\\b|\\bdoes not prove\\b"
  },
  vocabulary: [
    "Practical knowledge of how to do something",
    "Beginning to use a method or idea",
    "Shared by each side",
    "Lasting local ability to solve problems",
    "Exchanged in both directions",
    "A person who farms a small area",
    "The amount a crop produces",
    "A small area used to show a technique",
    "A practical test outside a laboratory",
    "A small project that tests delivery",
    "Whether something can work in practice",
    "Supplying water to crops through a system",
    "Resources put into production",
    "Money available before income arrives",
    "Able to continue successfully",
    "Work that keeps a system functioning",
    "Needing support from somewhere else",
    "Spread through a group or area",
    "Learning from people in a similar role",
    "How far people actually start using something",
    "Local influence over a programme",
    "Designed to seek relevant views",
    "Pay for something jointly",
    "Ability to obtain favourable terms",
    "A personal stake in one outcome",
    "Careful checks before a commitment",
    "A starting point for later comparison",
    "Linking a change to a particular cause",
    "Increase the reach of an activity",
    "Make a practice a regular part of a system"
  ],
  paragraphs: [
    {id:"A", title:"A manual is not a farming routine", tag:"Know-how and adoption", takeaway:"Success elsewhere is not, by itself, a reason to expect success here.", explanation:"A written manual can give planting distances and still say nothing about water or the right moment to harvest. Farmers have to judge their land, money and obligations. Cooperation is useful when it helps that judgement. It is not useful when it assumes a method must work wherever it arrives.", question:"Does technical merit settle the question?", answer:"No. Adoption depends on more than technical merits. The paragraph rejects the idea that success in one place is sufficient reason to expect success in another.", image:0, imageAlt:"Seedlings, irrigation pipes and seed travel across the sea from one farming coast to another, where farmers still have to judge them"},
    {id:"B", title:"Exchange should leave a local capacity", tag:"Mutual benefit and reciprocity", takeaway:"Partners can learn from each other without being the same.", explanation:"The 11 September UN feature is the occasion for the argument. Mutual benefit means both sides learn something useful. Capacity building means local people and organisations can continue after the visitors leave. Reciprocal exchange goes further: local experience also changes the advice outsiders give. Similar challenges can make a partner relevant. The label Global South does not mean identical resources, climates or political influence.", question:"What does reciprocal add to mutual?", answer:"Mutual describes something shared. Reciprocal describes an exchange that moves in both directions, including local experience changing outside advice."},
    {id:"C", title:"A demonstration is not an ordinary harvest", tag:"Reported yields and smallholders", takeaway:"These figures are programme results. They are not a national average.", explanation:"The April 2026 FAO account reports that more than 200 crop varieties were introduced and tested, four were released for commercial production, and hybrid rice at demonstration sites reached up to 6.9 tonnes per hectare. A smallholder still has to ask whether a higher yield is possible in ordinary conditions, with ordinary money and ordinary labour. A carefully managed plot can reveal potential without showing what every household can afford to copy.", question:"What does 6.9 tonnes per hectare not establish?", answer:"It does not establish a national average, an independent estimate of the partnership's effects, or what every household can reproduce.", image:5, imageAlt:"Specialists inspect a carefully watered rice demonstration, while a smallholder works a more ordinary field with a worn pump"},
    {id:"D", title:"A crop can succeed while a programme cannot", tag:"Field trial and pilot", takeaway:"Growing well and being affordable to continue are different tests.", explanation:"A field trial compares how a crop performs under stated conditions. A pilot project asks whether training, supply and cost can work on a limited scale. The crop may grow well even when the training is too expensive to continue. If farmers say the new calendar clashes with another harvest, that response is evidence. Calling it resistance throws the evidence away and gives people less reason to report problems honestly.", question:"Why can a successful trial still be a poor programme?", answer:"Biological performance does not test whether the delivery system can continue. Feasibility includes practical and organisational questions."},
    {id:"E", title:"Follow the chain past the harvest", tag:"Inputs, repair and viability", takeaway:"More output can still fail if water, repair, timing or prices do not work.", explanation:"Irrigation may carry a crop through dry weather, but the pump needs energy, spare parts and someone who can repair it. Seed and fertiliser have to arrive when the season needs them. A household with little capital may be unable to pay those costs before any income comes in. High transport costs or low prices can make the method commercially unviable. Maintenance and dependence on distant suppliers belong in the first calculation.", question:"Why is a higher yield not automatically a gain?", answer:"Costs, repair, transport and the prices buyers offer can remove the benefit. Viable adds the ability to continue, especially financially.", image:4, imageAlt:"A farm routine links a repaired water pump, deliveries of seed, household money, a truck on a difficult road and a market sale"},
    {id:"F", title:"Enthusiasm is not sustained use", tag:"Diffusion and uptake", takeaway:"A workshop count cannot tell you what people still use.", explanation:"A method may spread faster when farmers can look at a neighbour's field and ask awkward questions. Peer learning can include mistakes that a formal presentation leaves out. Visible enthusiasm is a weak substitute for sustained uptake. One household may try a method because the equipment is free, then drop it. Another may reject the package and keep one useful part. Follow-up has to ask what people still use, what they changed and why.", question:"What can attendance figures not separate?", answer:"Continued use, stopping when support ends, and keeping only one part of the method.", image:1, imageAlt:"Farmers stop along a village path to inspect a neighbour's crop and compare it with their own fields"},
    {id:"G", title:"Paying is not the same as being heard", tag:"Local ownership", takeaway:"A proposal to organise cooperation is not evidence of higher incomes.", explanation:"Local ownership means the people affected have a real influence on priorities and implementation. Consultation should include farmers whose land, income or household duties make it hard to attend. A government may co-finance a programme to show commitment. The payment does not prove that every affected group has been heard. The UN account published on 2 September describes a consultation on 27 August and a proposal for a regular cooperation platform. That is an ambition to organise exchange. It does not yet show higher farm incomes.", question:"What does the platform proposal not demonstrate?", answer:"Improved farm incomes. The paragraph separates an organisational proposal from a demonstrated economic result.", image:2, imageAlt:"Farmers and visiting partners discuss a model of fields and water, while a scale weighs equipment and money against community life"},
    {id:"H", title:"Look at power before anyone commits", tag:"Bargaining and due diligence", takeaway:"These are risks to examine, not accusations against the programmes named here.", explanation:"Partnerships can shorten the search for something that works, because one country can learn from another's mistakes. The critical questions are who chooses the technology and who sells the supplies. A partner with more bargaining power may shape the terms around its own commercial priorities. A supplier with a vested interest in one product may play down cheaper alternatives. Due diligence should make costs, responsibilities and alternatives visible before people commit.", question:"Does the writer say these programmes acted improperly?", answer:"No. The paragraph says the risks should be examined. It does not accuse the programmes it describes. Transparent agreements help cooperation earn trust."},
    {id:"I", title:"A later increase still needs a cause", tag:"Baseline and attribution", takeaway:"Better rainfall or higher prices can look like programme success.", explanation:"A baseline records conditions before a programme begins. A simple before-and-after rise may come from better rainfall or higher crop prices. Attribution asks how much of the change can reasonably be linked to the programme. Where possible, compare similar participants and non-participants, and look for differences that could distort the comparison. Also ask whether the gains remain after intensive support ends. A decision to scale up needs evidence from ordinary delivery, not only from the most impressive showcase.", question:"Why is a before-and-after increase not enough?", answer:"Something other than the programme, such as rainfall or prices, may explain it. The increase does not, by itself, prove the programme was the cause.", image:3, imageAlt:"The same farming landscape sits under rain and sun, with irrigation, a market truck, note-takers and farmers comparing crops"},
    {id:"J", title:"Leave the next judgement local", tag:"Institutionalise, without freezing practice", takeaway:"Success means a community can assess the next technique for itself.", explanation:"Training budgets, local advisers and reliable feedback channels can keep useful knowledge alive while still letting it change. A sensible partnership expands gradually, publishes disappointing results and revises its methods when conditions change. Moving a technique from one country to another is not the whole success. The route depends on careful testing, shared decisions and learning in both directions.", question:"What would count as more than a transfer?", answer:"Communities left better able to judge the next technique for themselves, rather than only receiving this one."}
  ],
  grammar: [
    {label:"A RESULT WITH A LIMIT", title:"Show the potential. Then stop the conclusion.", chunks:["A carefully managed demonstration plot may reveal potential", "without showing", "what every household can afford to reproduce."], roles:["Main clause: a possibility", "Preposition plus -ing", "Object of showing"], tip:"May keeps the claim possible rather than universal. After without, use the -ing form."},
    {label:"A STRENGTH WITH A CONDITION", title:"More output can still fail the money test.", chunks:["Even a technique that raises output", "may not be commercially viable", "if transport is expensive or buyers offer low prices."], roles:["Noun plus a relative clause", "Possible negative result", "Two conditions joined by or"], tip:"Even marks a surprising limit. May not means possible failure, not certain failure."},
    {label:"WHO SHOULD BE INCLUDED", title:"Name the barrier, not only the principle.", chunks:["A consultative process should therefore include farmers", "whose land, income or household duties", "make participation difficult."], roles:["Recommendation", "Whose links the farmers to their circumstances", "make plus object plus adjective"], tip:"Whose attaches the barrier to the farmers. Should makes this a recommendation."},
    {label:"AN ACTION AND WHAT IT CANNOT PROVE", title:"Separate the payment from the conclusion.", chunks:["Governments may co-finance a programme to demonstrate commitment,", "but a financial contribution alone does not establish", "that every affected group has been heard."], roles:["Purpose: to demonstrate", "Contrast and a limit on proof", "Present perfect passive"], tip:"To demonstrate gives the purpose. Alone limits what the payment can prove. Has been heard asks whether consultation happened."},
    {label:"A CONDITION FOR GROWING", title:"Connect the intended expansion to its evidence.", chunks:["If a programme is to scale up,", "evidence about ordinary delivery conditions matters more", "than its most impressive showcase."], roles:["be to plus infinitive: an intended outcome", "Singular evidence matters", "Comparison with the best example"], tip:"Is to scale up points to an intended future. Evidence is singular, so the verb is matters."}
  ],
  diagrams: {
    C: {type:"compare", title:"What the reported figures do and do not show", subtitle:"FAO account in paragraph C", items:[["Reported", "More than 200 varieties were tested, four were released, and hybrid rice at demonstration sites reached up to 6.9 tonnes per hectare."], ["Not established", "A national average, an independent estimate of the partnership's effects, or what every household can afford to reproduce."]]},
    D: {type:"compare", title:"A field trial and a pilot ask different questions", subtitle:"The hypothetical village in paragraph D", items:[["Field trial", "Compares performance under specified conditions. The crop may grow well."], ["Pilot project", "Tests whether delivery can work on a limited scale. The training may still be too expensive to continue."]]},
    F: {type:"choices", title:"What a workshop count cannot separate", subtitle:"Later outcomes in paragraph F", options:[["Still in use", "Follow-up finds that people still use the method, or a version they have changed. That is evidence of uptake."], ["Tried, then stopped", "The equipment was free, so a household tried the method and abandoned it when support ended."], ["Kept one part", "The household rejected the full package but retained one useful element. Attendance cannot show this."]]},
    H: {type:"compare", title:"A reason to cooperate, and a reason to look closely", subtitle:"Paragraph H · questions to examine, not accusations", items:[["The case for a partnership", "Learning from another country's mistakes may save time and money."], ["The case for scrutiny", "Ask who chooses the technology, who sells the supplies, and which cheaper alternatives are left out."]]},
    I: {type:"choices", title:"What else could explain an apparent improvement?", subtitle:"Paragraph I · a before-and-after change", options:[["The programme", "This is the claim attribution has to test. Timing alone does not link the change to the programme."], ["Better rainfall", "Weather can raise output whether or not the programme worked."], ["Higher crop prices", "A price change can alter the result without proving that the technique itself succeeded."]]}
  }
};
